name: Build and Deploy

on:
  push:
    branches:
      - main # 此处如果你是 master 分支，请改成 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 根据项目使用的是 node 20 或 22

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # 这将产生 dist 产物

      - name: Clear Old Files & Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/*"
          target: "/var/www/studio/dist"
          strip_components: 1 # 去掉 dist 这一层目录，直接放到 target 下
